version: '3.1'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=user-accounts
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5433:5432'
    volumes:
      - ./docker-data/user-accounts:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    environment:
      - PORT=3000
      - JWT_SECRET=super_secret
      - DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:5433/user-accounts
    ports:
      - '3000:3000'
    depends_on:
      - postgres
