version: '3.1'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "user"
      POSTGRES_DB: "user-accounts"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 3s
      retries: 30
    volumes:
      - ./docker-data/db:/var/lib/postgresql/data
